Repository Sprint-11-5team/WHYNE, pull requests merged in 2024-12, with the labels that each got.

#26 [feat] 21 공통 버튼 컴포넌트
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  next.config.ts
  package-lock.json
  package.json
  src/app/test/page.tsx
  src/components/common/Button.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature, 🎨 CSS

#51 [feat]14 공용api기능 작업
  api-test.http
  package-lock.json
  package.json
  src/api/api.ts
Labels: ⚙️ Setting

#64 Features/11 회원가입 입력창 틀 구현
  src/app/signup/page.tsx
  src/components/auth/input-item.tsx
  src/components/auth/signup-form.tsx
  src/components/common/container.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature, 🎨 CSS

#63 feat: 공용 input component
  package-lock.json
  package.json
  src/app/input-test/page.tsx
  src/components/common/Input.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature

#65 feat: 공용 modal container
  src/app/test-base-modal/page.tsx
  src/components/common/Modal-container.tsx
Labels: ✨ Feature

#67 feat: add types for wine tasting interface
  src/types/tasting.ts
Labels: ✨ Feature

#73 [login]52 로그인 입력창 구현
  package-lock.json
  package.json
  src/app/signin/page.tsx
  src/components/common/singin/input-item.tsx
  src/components/common/singin/signin-form.tsx
Labels: ✨ Feature, 🎨 CSS

#74 [feat] 28 landing main 구현
  public/icons/gray_star.svg
  public/icons/purple_logo.svg
  public/images/fifth_card_top.svg
  public/images/filter_wine.svg
  public/images/first_card_top.svg
  public/images/fourth_card_top.svg
  public/images/middle_first_card.svg
  public/images/middle_second_card.svg
  public/images/mobile_filter_wine.svg
  public/images/mobile_review.svg
  public/images/prices_filter.svg
  public/images/review.svg
  public/images/second_card_top.svg
  public/images/third_card_top.svg
  public/images/types_filter.svg
  src/app/page.tsx
  src/app/test/page.tsx
  src/components/common/Button.tsx
  src/components/landing/CardList.tsx
  src/components/landing/SectionCard.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature, 🎨 CSS

#82 Features/12 회원가입 유효성 검사 및 에러 메시지
  package-lock.json
  package.json
  src/app/signup/page.tsx
  src/components/auth/ rules.ts
  src/components/auth/input-item.tsx
  src/components/auth/signup-form.tsx
  src/types/rules.d.ts
Labels: ✨ Feature, 🎨 CSS

#91 [feat] 12/19 78 wines 목록페이지 UI 구현 1차
  public/icons/small_search.svg
  public/images/sample_wine.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/app/wines/page.tsx
  src/components/common/Nav.tsx
  src/components/wines/Card.tsx
  src/components/wines/CardList.tsx
  src/components/wines/FilterButton.tsx
  src/components/wines/PriceFilter.tsx
  src/components/wines/RatingFilter.tsx
  src/components/wines/SearchBar.tsx
  src/components/wines/TypesFilter.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature, 🎨 CSS

#83 [login] 54 로그인 기능구현
  api-test.http
  src/api/api.ts
  src/app/signin/page.tsx
  src/components/auth/input-item.tsx
  src/components/auth/signin-form.tsx
  src/components/common/singin/input-item.tsx
  src/components/common/singin/signin-form.tsx
Labels: ✨ Feature

#96 Feat: Features/84 회원가입 회원 정보 생성 api
  src/components/auth/input-item.tsx
  src/components/auth/signup-form.tsx
Labels: ✨ Feature, 🎨 CSS

#104 Feat: 토큰 로컬 스토리지 저장
  src/api/api.ts
  src/components/auth/signup-form.tsx
  src/context/auth-provider.tsx
Labels: ✨ Feature

#114 109 무한스크롤 페이지 무한스크롤기능
  src/app/infinitetest/page.tsx
  src/components/InfiniteScroll/infiniteScroll.tsx
Labels: ✨ Feature

#128 127 로그인 카카오oauth 등록
  src/api/api.ts
  src/components/auth/KakaoLoginButton.tsx
  src/components/auth/signin-form.tsx
Labels: ✨ Feature

#123 [/wines] (12/23) 90 wines 기능붙이기 2차 css수정
  package-lock.json
  package.json
  public/icons/purple_star.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/app/wines/page.tsx
  src/components/common/Nav.tsx
  src/components/wines/Card.tsx
  src/components/wines/CardList.tsx
  src/components/wines/RatingFilter.tsx
  src/components/wines/SearchBar.tsx
  src/components/wines/TypesFilter.tsx
  src/components/wines/entire-card.tsx
  src/components/wines/filter-button.tsx
  src/components/wines/price-filter.tsx
  src/components/wines/rating-filter.tsx
  src/components/wines/recommend-card.tsx
  src/components/wines/search.tsx
  src/components/wines/types-filter.tsx
  src/styles/globals.css
Labels: ✨ Feature, 🎨 CSS

#125 Feat: AuthProvider(전역 로그인 유지)
  src/api/api.ts
  src/app/layout.tsx
  src/components/auth/signin-form.tsx
  src/components/auth/signup-form.tsx
  src/components/common/Nav.tsx
  src/context/auth-provider.tsx
  src/types/auth.ts
Labels: 🛠️ Refactor, ✨ Feature

#130 Style: 회원가입 반응형 구현
  src/app/layout.tsx
  src/app/signup/page.tsx
  src/components/auth/input-item.tsx
  src/components/auth/signup-form.tsx
  src/components/common/nav-wrapper.tsx
Labels: 🛠️ Refactor, 🎨 CSS

#136 129 로그인 카카오톡 로그인 api
  api-test.http
  src/api/api.ts
  src/app/signin/page.tsx
  src/components/auth/KakaoLoginButton.tsx
Labels: ✨ Feature

#148 [feat] (12/25) 모달 내용 수정 / 90 wines 기능붙이기 1차 css수정
  src/app/wines/page.tsx
  src/components/common/Nav.tsx
  src/components/wines/modal/filter-modal.tsx
  src/components/wines/search.tsx
  tailwind.config.ts
Labels: 🛠️ Refactor, ✨ Feature, 🎨 CSS

#150 Fix: 로그인이 필요합니다 alert 반복 노출 오류 해결
  src/api/api.ts
  src/app/signup/page.tsx
  src/app/wines/[wineid]/page.tsx
  src/components/auth/signup-form.tsx
  src/components/wines/detail/detail-review-card.tsx
  src/components/wines/detail/detail-wine-card.tsx
  src/components/wines/detail/rating-details.tsx
  src/context/auth-provider.tsx
Labels: 🐞 Bug, ✨ Feature

#149 [style] 138 wines 필터 모달 구현
  public/icons/x_button.svg
  src/components/common/modal-container.tsx
  src/components/wines/modal/filter-modal.tsx
  src/components/wines/price-filter.tsx
  src/components/wines/rating-filter.tsx
  src/components/wines/types-filter.tsx
Labels: ✨ Feature, 🎨 CSS

#156 리프레시 토큰발급
  src/app/signin/page.tsx
Labels: ✨ Feature

#158 Feat: 와인상세 종합 별점 보여주기
  src/app/wines/[wineid]/page.tsx
  src/components/wines/detail/detail-review-card.tsx
  src/components/wines/detail/rating-details.tsx
  src/context/auth-provider.tsx
Labels: ✨ Feature, 🎨 CSS

#151 test페이지, 무한스크롤 구현완료
  src/app/infinitetest/page.tsx
Labels: ✨ Feature

#161 [feat] (12/26) 초기화 버튼 시각적 작동 추가
  src/app/wines/page.tsx
  src/components/wines/modal/filter-modal.tsx
  src/components/wines/price-filter.tsx
  src/components/wines/rating-filter.tsx
  src/components/wines/wine.ts
Labels: ✨ Feature, 🎨 CSS

#175 Feat: 리뷰 등록하기 모달 api
  src/components/common/Slider.tsx
  src/components/modal-review/AddReviewModal.tsx
  src/components/modal-review/ReviewInput.tsx
  src/components/modal-review/TagSelector.tsx
  src/components/modal-review/TasteSlider.tsx
  src/components/wines/detail/detail-review-card.tsx
  src/components/wines/detail/detail-wine-tag.tsx
  src/components/wines/detail/rating-details.tsx
  src/provider/usereviewmodals.tsx
Labels: 🛠️ Refactor, ✨ Feature

#181 [refactor] (12/28) 목록 페이지 refactoring
  src/app/wines/page.tsx
  src/components/wines/entire-card.tsx
  src/components/wines/modal/filter-modal.tsx
  src/components/wines/price-filter.tsx
  src/components/wines/rating-filter.tsx
  src/components/wines/wine.ts
  src/types/tasting.ts
Labels: 🛠️ Refactor

#183 [ 무한스크롤] 최신버전 무한스크롤
  src/components/InfiniteScroll/use-infiniteScroll.tsx
  src/components/myprofile/profile-tab.tsx
Labels: ✨ Feature

#185 Fix: 리뷰 등록 수정 api 오류 해결 & 리뷰 수정하기 완성
  src/app/layout.tsx
  src/app/review-test/page.tsx
  src/app/test/addwine/page.tsx
  src/app/test/input-test/page.tsx
  src/app/test/page.tsx
  src/app/test/test-base-modal/page.tsx
  src/app/test/test-button/page.tsx
  src/app/test/test-modal-delete/page.tsx
  src/components/modal-review/AddReviewModal.tsx
  src/components/modal-review/ReviewInput.tsx
  src/components/modal-review/TagSelector.tsx
  src/components/modal-review/TasteSlider.tsx
  src/components/modal-review/modal-review-edit.tsx
  src/components/modal-wine/modal-add-wine.tsx
  src/components/modal-wine/modal-eddit-wine.tsx
  src/components/myprofile/my-review-card.tsx
  src/components/wines/detail/detail-no-review.tsx
  src/components/wines/detail/detail-review-card.tsx
  src/components/wines/detail/rating-details.tsx
  src/provider/usereviewmodals.tsx
Labels: 🐞 Bug, 🛠️ Refactor

#194 Fix: review modal api
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/modal-review/AddReviewModal.tsx
  src/components/wines/detail/detail-no-review.tsx
  src/components/wines/detail/detail-review-card.tsx
  src/components/wines/detail/rating-details.tsx
Labels: 🐞 Bug
